/**
 * Cross-Vector Forensic and Threat Intelligence Correlation Framework
 * DFIR Investigation Report Generator & Exporter
 */

export class DFIRReportGenerator {
  static generateReportMarkdown(correlationResult, confidenceAssessment, incidents) {
    const incA = incidents[0] || {};
    const incB = incidents[1] || {};
    const timestamp = new Date().toUTCString();

    let md = `# DIGITAL FORENSICS & INCIDENT RESPONSE (DFIR) INVESTIGATION REPORT
**Multi-Vector Cross-Correlation & Threat Intelligence Attribution Assessment**
*Generated by Antigravity Cross-Vector Forensic Framework*
*Date: ${timestamp}*

---

## 1. EXECUTIVE SUMMARY & ATTRIBUTION VERDICT

- **Correlation Verdict:** ${confidenceAssessment.verdict}
- **Attribution Confidence Level:** **${confidenceAssessment.level}** (Score: ${confidenceAssessment.score}/100)
- **Attributed Threat Actor:** ${correlationResult.summary?.threatActorCandidate || 'Unclassified'}
- **Primary Hypothesis:** ${confidenceAssessment.explanation}
- **Counter-Hypothesis Analysis:** ${confidenceAssessment.counterHypothesis}

---

## 2. INCIDENTS UNDER INVESTIGATION

### Primary Incident A:
- **Incident ID:** ${incA.id}
- **Title:** ${incA.title}
- **Vector:** ${incA.vectorType}
- **Target User / Asset:** ${incA.targetedUser || 'N/A'} | ${incA.asset || 'N/A'}

### Secondary Incident B:
- **Incident ID:** ${incB.id}
- **Title:** ${incB.title}
- **Vector:** ${incB.vectorType}
- **Target User / Asset:** ${incB.targetedUser || 'N/A'} | ${incB.asset || 'N/A'}

---

## 3. MULTI-DIMENSIONAL CORRELATION BREAKDOWN

| Dimension | Raw Score | Weight | Contribution | Evidentiary Rationale |
| :--- | :---: | :---: | :---: | :--- |
`;

    confidenceAssessment.breakdown.forEach(b => {
      md += `| **${b.displayName}** | ${b.rawScore}/100 | ${b.weightPercentage}% | +${b.contribution} pts | ${b.rationale} |\n`;
    });

    md += `\n**Total Weighted Attribution Score:** **${confidenceAssessment.score} / 100**\n\n`;

    md += `---

## 4. SHARED FORENSIC INDICATORS & INFRASTRUCTURE MATRIX

`;

    if (correlationResult.sharedEntities && correlationResult.sharedEntities.length > 0) {
      md += `| Indicator Type | Value | Correlation Relevance |\n`;
      md += `| :--- | :--- | :--- |\n`;
      correlationResult.sharedEntities.forEach(s => {
        md += `| \`${s.type}\` | **\`${s.value}\`** | ${s.label || 'Cross-Incident Overlap'} |\n`;
      });
    } else {
      md += `*No direct shared IOCs or infrastructure nexus detected between vectors.*\n`;
    }

    md += `\n---

## 5. RECONSTRUCTED ATTACK TIMELINE & CAUSALITY

`;

    const allEvents = [];
    incidents.forEach(inc => {
      (inc.evidence || []).forEach(e => {
        allEvents.push({ ...e, incName: inc.title });
      });
    });
    allEvents.sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());

    allEvents.forEach(e => {
      md += `- **[${e.timestamp}]** [${e.severity.toUpperCase()}] **${e.title}** (${e.incName})\n  *${e.description}*\n`;
    });

    md += `\n---

## 6. RECOMMENDED CONTAINMENT & REMEDIATION PLAYBOOK

`;

    confidenceAssessment.recommendedActions.forEach((act, i) => {
      md += `${i + 1}. ${act}\n`;
    });

    md += `\n---
*CONFIDENTIAL - FOR INTERNAL DFIR / LEGAL USE ONLY*
`;

    return md;
  }

  static renderReportHTML(containerId, correlationResult, confidenceAssessment, incidents) {
    const container = document.getElementById(containerId);
    if (!container) return;

    const markdown = this.generateReportMarkdown(correlationResult, confidenceAssessment, incidents);
    
    // Render formatted report card
    container.innerHTML = `
      <div class="report-actions-toolbar">
        <button id="btnDownloadMd" class="btn btn-secondary">📥 Export Markdown Report</button>
        <button id="btnDownloadJson" class="btn btn-secondary">💾 Export JSON Forensic Bundle</button>
        <button id="btnPrintReport" class="btn btn-primary">🖨️ Print / Save as PDF</button>
      </div>
      <div class="dfir-report-document" id="printableReport">
        <div class="report-header">
          <div class="report-badge">SECURITY OPERATIONS & DFIR LABS</div>
          <h2 class="report-main-title">Cross-Vector Forensic & Threat Intelligence Correlation Report</h2>
          <div class="report-sub">Automated Attribution & Evidence Coherence Assessment</div>
        </div>

        <div class="verdict-banner verdict-${confidenceAssessment.level.toLowerCase()}">
          <div class="verdict-icon">${confidenceAssessment.level === 'HIGH' ? '🚨' : (confidenceAssessment.level === 'MEDIUM' ? '⚠️' : 'ℹ️')}</div>
          <div class="verdict-text-block">
            <div class="verdict-level">ATTRIBUTION CONFIDENCE: ${confidenceAssessment.level} (${confidenceAssessment.score}/100)</div>
            <h3 class="verdict-headline">${confidenceAssessment.verdict}</h3>
            <p class="verdict-narrative">${confidenceAssessment.explanation}</p>
          </div>
        </div>

        <section class="report-section">
          <h3 class="section-title">1. Incidents Overview</h3>
          <div class="incident-compare-grid">
            ${incidents.map(inc => `
              <div class="inc-summary-card">
                <h4>${inc.title}</h4>
                <div class="inc-prop"><span>Vector:</span> <strong>${inc.vectorType}</strong></div>
                <div class="inc-prop"><span>Target:</span> <strong>${inc.targetedUser || 'N/A'}</strong></div>
                <div class="inc-prop"><span>Asset:</span> <strong>${inc.asset || 'N/A'}</strong></div>
                <div class="inc-prop"><span>Evidence Records:</span> <strong>${(inc.evidence || []).length} artifacts</strong></div>
              </div>
            `).join('')}
          </div>
        </section>

        <section class="report-section">
          <h3 class="section-title">2. Multi-Dimensional Correlation Matrix</h3>
          <table class="dfir-table">
            <thead>
              <tr>
                <th>Correlation Dimension</th>
                <th>Score</th>
                <th>Weight</th>
                <th>Contribution</th>
                <th>Evidentiary Reasoning</th>
              </tr>
            </thead>
            <tbody>
              ${confidenceAssessment.breakdown.map(b => `
                <tr>
                  <td><strong>${b.displayName}</strong></td>
                  <td><span class="score-pill score-${b.rawScore >= 70 ? 'high' : (b.rawScore >= 40 ? 'med' : 'low')}">${b.rawScore}/100</span></td>
                  <td>${b.weightPercentage}%</td>
                  <td><strong>+${b.contribution}</strong></td>
                  <td>${b.rationale}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </section>

        <section class="report-section">
          <h3 class="section-title">3. Shared Nexus Indicators & Infrastructure</h3>
          ${correlationResult.sharedEntities && correlationResult.sharedEntities.length > 0 ? `
            <table class="dfir-table">
              <thead>
                <tr>
                  <th>Indicator Type</th>
                  <th>Indicator Value</th>
                  <th>Correlation Assessment</th>
                </tr>
              </thead>
              <tbody>
                ${correlationResult.sharedEntities.map(s => `
                  <tr>
                    <td><code>${s.type}</code></td>
                    <td><strong class="highlight-ioc">${s.value}</strong></td>
                    <td>${s.label || 'Cross-Incident Overlap'}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          ` : '<p class="text-muted">No shared indicators found across the investigated vectors.</p>'}
        </section>

        <section class="report-section">
          <h3 class="section-title">4. Recommended DFIR Response & Remediation Plan</h3>
          <ol class="action-list">
            ${confidenceAssessment.recommendedActions.map(act => `<li>${act}</li>`).join('')}
          </ol>
        </section>
      </div>
    `;

    // Hook up buttons
    document.getElementById('btnDownloadMd')?.addEventListener('click', () => {
      const blob = new Blob([markdown], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `DFIR_Correlation_Report_${incidents[0]?.id || 'Case'}.md`;
      a.click();
    });

    document.getElementById('btnDownloadJson')?.addEventListener('click', () => {
      const exportBundle = {
        generatedAt: new Date().toISOString(),
        correlationResult,
        confidenceAssessment,
        incidents
      };
      const blob = new Blob([JSON.stringify(exportBundle, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `DFIR_Forensic_Bundle_${incidents[0]?.id || 'Case'}.json`;
      a.click();
    });

    document.getElementById('btnPrintReport')?.addEventListener('click', () => {
      window.print();
    });
  }
}
